USE [master]
GO
/****** Object:  Database [MeetingScheduler]    Script Date: 7/5/2017 7:59:05 PM ******/
CREATE DATABASE [MeetingScheduler]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeetingScheduler', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\MeetingScheduler.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MeetingScheduler_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\MeetingScheduler_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MeetingScheduler] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeetingScheduler].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MeetingScheduler] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MeetingScheduler] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MeetingScheduler] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MeetingScheduler] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MeetingScheduler] SET ARITHABORT OFF 
GO
ALTER DATABASE [MeetingScheduler] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MeetingScheduler] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MeetingScheduler] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MeetingScheduler] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MeetingScheduler] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MeetingScheduler] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MeetingScheduler] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MeetingScheduler] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MeetingScheduler] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MeetingScheduler] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MeetingScheduler] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MeetingScheduler] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MeetingScheduler] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MeetingScheduler] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MeetingScheduler] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MeetingScheduler] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MeetingScheduler] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MeetingScheduler] SET RECOVERY FULL 
GO
ALTER DATABASE [MeetingScheduler] SET  MULTI_USER 
GO
ALTER DATABASE [MeetingScheduler] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MeetingScheduler] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MeetingScheduler] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MeetingScheduler] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MeetingScheduler] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MeetingScheduler', N'ON'
GO
ALTER DATABASE [MeetingScheduler] SET QUERY_STORE = OFF
GO
USE [MeetingScheduler]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [MeetingScheduler]
GO
/****** Object:  User [MeetingScheduler]    Script Date: 7/5/2017 7:59:05 PM ******/
CREATE USER [MeetingScheduler] FOR LOGIN [MeetingScheduler] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [MeetingScheduler]
GO
/****** Object:  Table [dbo].[Appointment]    Script Date: 7/5/2017 7:59:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Appointment](
	[AppointmentID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[VenueID] [int] NOT NULL,
	[Time] [datetime] NOT NULL,
 CONSTRAINT [PK_Appointment] PRIMARY KEY CLUSTERED 
(
	[AppointmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Meeting]    Script Date: 7/5/2017 7:59:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Meeting](
	[MeetingID] [int] IDENTITY(1,1) NOT NULL,
	[VenueID] [int] NOT NULL,
	[Time] [datetime] NOT NULL,
	[Subject] [varchar](max) NOT NULL,
	[Confirmed] [bit] NOT NULL,
 CONSTRAINT [PK_Meeting] PRIMARY KEY CLUSTERED 
(
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Negotiation]    Script Date: 7/5/2017 7:59:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Negotiation](
	[UserID] [int] NOT NULL,
	[MeetingID] [int] NOT NULL,
	[RequestedVenueID] [int] NOT NULL,
	[RequestedTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Negotiation] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 7/5/2017 7:59:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](max) NOT NULL,
	[Email] [varchar](max) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserMeeting]    Script Date: 7/5/2017 7:59:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserMeeting](
	[UserID] [int] NOT NULL,
	[MeetingID] [int] NOT NULL,
 CONSTRAINT [PK_UserMeeting] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Venue]    Script Date: 7/5/2017 7:59:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Venue](
	[VenueID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](max) NOT NULL,
	[Address] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Venue] PRIMARY KEY CLUSTERED 
(
	[VenueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Meeting] ADD  CONSTRAINT [DF_Meeting_Confirmed]  DEFAULT ((0)) FOR [Confirmed]
GO
ALTER TABLE [dbo].[Appointment]  WITH CHECK ADD  CONSTRAINT [FK_Appointment_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
GO
ALTER TABLE [dbo].[Appointment] CHECK CONSTRAINT [FK_Appointment_User]
GO
ALTER TABLE [dbo].[Appointment]  WITH CHECK ADD  CONSTRAINT [FK_Appointment_Venue] FOREIGN KEY([VenueID])
REFERENCES [dbo].[Venue] ([VenueID])
GO
ALTER TABLE [dbo].[Appointment] CHECK CONSTRAINT [FK_Appointment_Venue]
GO
ALTER TABLE [dbo].[Meeting]  WITH CHECK ADD  CONSTRAINT [FK_Meeting_Venue] FOREIGN KEY([VenueID])
REFERENCES [dbo].[Venue] ([VenueID])
GO
ALTER TABLE [dbo].[Meeting] CHECK CONSTRAINT [FK_Meeting_Venue]
GO
ALTER TABLE [dbo].[Negotiation]  WITH CHECK ADD  CONSTRAINT [FK_Negotiation_Meeting] FOREIGN KEY([MeetingID])
REFERENCES [dbo].[Meeting] ([MeetingID])
GO
ALTER TABLE [dbo].[Negotiation] CHECK CONSTRAINT [FK_Negotiation_Meeting]
GO
ALTER TABLE [dbo].[Negotiation]  WITH CHECK ADD  CONSTRAINT [FK_Negotiation_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
GO
ALTER TABLE [dbo].[Negotiation] CHECK CONSTRAINT [FK_Negotiation_User]
GO
ALTER TABLE [dbo].[UserMeeting]  WITH CHECK ADD  CONSTRAINT [FK_UserMeeting_Meeting] FOREIGN KEY([MeetingID])
REFERENCES [dbo].[Meeting] ([MeetingID])
GO
ALTER TABLE [dbo].[UserMeeting] CHECK CONSTRAINT [FK_UserMeeting_Meeting]
GO
ALTER TABLE [dbo].[UserMeeting]  WITH CHECK ADD  CONSTRAINT [FK_UserMeeting_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
GO
ALTER TABLE [dbo].[UserMeeting] CHECK CONSTRAINT [FK_UserMeeting_User]
GO
USE [master]
GO
ALTER DATABASE [MeetingScheduler] SET  READ_WRITE 
GO
